---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Dashboard"
subtitle: "Home.Lab"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.
columns: "4" #Added extra parameter - PSF 18/10/21

# Optional theme customization
theme: dark
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message
#message:
#  #url: https://b4bz.io
##  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#  title: "Demo !"
#  icon: "fa fa-grin"
#  content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "fa icons"
    icon: "fab fa-font-awesome"
    url: "https://fontawesome.com/v5.15/icons/"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
  - name: "another page!"
    icon: "fas fa-file-alt"
    url: "#additionnal-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Firewalls & Switches"
    icon: "fas fa-cloud"
    items:
      - name: "Pedro-pfsense-01"
        logo: "assets/images/pfsense-logo.png"
        subtitle: "Central Firewall"
        tag: "Firewall"
        url: "https://pedro-pfsense-01.home.lab/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-pfsense-02"
        logo: "assets/images/pfsense-logo.png"
        subtitle: "DC01 Border Firewall"
        tag: "Firewall"
        url: "https://pedro-pfsense-02.home.lab/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-pfsense-03"
        logo: "assets/images/pfsense-logo.png"
        subtitle: "DC02 Border Firewall"
        tag: "Firewall"
        url: "https://pedro-pfsense-03.home.lab/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-opnsense-01"
        logo: "assets/images/opnsense.png"
        subtitle: "Border Firewall"
        tag: "Firewall"
        url: "https://192.168.201.82/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-SWCH-01"
        logo: "assets/images/netgear.png"
        subtitle: "Core Switch"
        tag: "Switch"
        url: "http://Pedro-SWCH-01.home.lab"
        target: "_blank" # optional html a tag target attribute

  - name: "Hosts & Storage"
    icon: "fas fa-server"
    items:
      - name: "Pedro-host-01"
        logo: "assets/images/esxi.jpg"
        subtitle: "Black Box"
        #type: Ping
        tag: "Hosts"
        url: "https://pedro-host-01.home.lab/ui/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-host-02"
        logo: "assets/images/esxi.jpg"
        subtitle: "Storage Host"
        tag: "Hosts"
        url: "https://pedro-host-02.home.lab/ui/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-ESXi-01"
        logo: "assets/images/esxi.jpg"
        subtitle: "ESXi 1"
        tag: "Hosts"
        url: "https://pedro-esxi-01.home.lab/ui/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-ESXi-02"
        logo: "assets/images/esxi.jpg"
        subtitle: "ESXi 2"
        tag: "Hosts"
        url: "https://pedro-esxi-02.home.lab/ui/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-ESXi-03"
        logo: "assets/images/esxi.jpg"
        subtitle: "ESXi 3"
        tag: "Hosts"
        url: "https://pedro-esxi-03.home.lab/ui/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-TrueNAS-01"
        logo: "assets/images/trueNAS.jpg"
        subtitle: "TrueNAS"
        tag: "Storage"
        url: "https://truenas.home.lab"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-NAS-Raid"
        logo: "assets/images/trueNAS.jpg"
        subtitle: "TrueNAS"
        tag: "Storage"
        url: "http://pedro-nas-raid:3080/cgi-bin/"
        target: "_blank" # optional html a tag target attribute

  - name: "Admin"
    icon: "fas fa-eye"
    items:
      - name: "Pedro-VCen-01"
        logo: "assets/images/esxi.jpg"
        subtitle: "vCentre"
        tag: "Admin"
        url: "https://Pedro-VCen-01.home.lab/ui/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-Logs-01"
        logo: "assets/images/kibana.png"
        subtitle: "Kibana - ELK"
        tag: "Admin"
        url: "http://pedro-logs-01.home.lab:5601/"
        target: "_blank" # optional html a tag target attribute
      - name: "IPAM"
        logo: "assets/images/phpipam_icon.png"
        subtitle: "IP Address Management"
        tag: "Admin"
        url: "http://pedro-docker-01.home.lab:3080/"
        target: "_blank" # optional html a tag target attribute
      - name: "Guacamole"
        logo: "assets/images/guacamole.png"
        subtitle: "Remote Management"
        tag: "Admin"
        url: "http://dockerdmz.home.lab:8080/guacamole/"
        target: "_blank" # optional html a tag target attribute

  - name: "Proxies"
    icon: "fas fa-shield-alt"
    items:
      - name: "Pedro-BIGIP-01"
        logo: "assets/images/f5.png"
        subtitle: "BIG-IP 01"
        tag: "Proxy"
        url: "https://Pedro-BIGIP-01.home.lab/tmui/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-BIGIP-02"
        logo: "assets/images/f5.png"
        subtitle: "BIG-IP 02"
        tag: "Proxy"
        url: "https://Pedro-BIGIP-02.home.lab/tmui/"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-MCRV-01"
        logo: "assets/images/mcafee-web-gateway.jpg"
        subtitle: "McAfee Proxy"
        tag: "Proxy"
        url: "https://Pedro-MCRV-01.home.lab:4712/Konfigurator/html/"
        target: "_blank" # optional html a tag target attribute

  - name: "Web Apps"
    icon: "fas fa-microchip"
    items:
      - name: "Pedro-WEB-01"
        logo: "assets/images/webserver.jpg"
        subtitle: "Web 1"
        tag: "App"
        url: "http://pedro-web-01.home.lab"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-WEB-01"
        logo: "assets/images/webserver.jpg"
        subtitle: "Web 2"
        tag: "App"
        url: "http://pedro-web-02.home.lab"
        target: "_blank" # optional html a tag target attribute
      - name: "Pedro-WEB-03"
        logo: "assets/images/webserver.jpg"
        subtitle: "Web 3"
        tag: "App"
        url: "http://pedro-web-03.home.lab"
        target: "_blank" # optional html a tag target attribute
